version: '2'

services:
  database:
    image: postgres:9.6
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./_data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
